<?php
use Insight\Entities\Contract;
/**
 *
 */
class ContractsTableSeeder extends Seeder
{

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        Contract::truncate();

        Contract::create(array(
            "web_id" => "2",
            "code" => "11052",
            "cname" => "Plaza Center - (compound 1)",
            "name" => "11052 - Plaza Center",
            "created_time" => "2014-06-03 10:07:15",
            "update_time" => "2014-06-03 10:07:15",
            "customer" => "General",
            "website" => "Main Website",
            "store" => "Default Store View",
            "name_bill" => "36 Strategies",
            "street_bill" => "H Hotel Office Tower",
            "street1_bill" => "Sheikh Zayed Road, Suite 2002",
            "city_bill" => "Dubai",
            "country_bill" => "AE",
            "zip_bill" => null,
            "name_ship1" => "36S",
            "street_ship1" => "36S",
            "street1_ship1" => "SZR",
            "city_ship1" => "Dubai",
            "country_ship1" => "AE",
            "zip_ship1" => null,
            "name_ship2" => "36S2",
            "street_ship2" => "36S2",
            "street1_ship2" => "36S2-L2",
            "city_ship2" => "Dubai",
            "country_ship2" => "AE",
            "zip_ship2" => null,
            "name_ship3" => null,
            "street_ship3" => null,
            "street1_ship3" => null,
            "city_ship3" => null,
            "country_ship3" => "0",
            "zip_ship3" => null,
            "name_ship4" => null,
            "street_ship4" => null,
            "street1_ship4" => null,
            "city_ship4" => null,
            "country_ship4" => "0",
            "zip_ship4" => null,
            "name_ship5" => null,
            "street_ship5" => null,
            "street1_ship5" => null,
            "city_ship5" => null,
            "country_ship5" => "0",
            "zip_ship5" => null,
            "user1" => "36S Storekeeper",
            "user2" => "36S Project Manager",
            "user3" => "36S Finance Manager",
            "user4" => null,
            "user5" => null,
            "user6" => null,
            "user7" => null,
            "user8" => null,
            "user9" => null,
            "user10" => null,
            "user11" => null,
            "user12" => null,
            "user13" => null,
            "user14" => null,
            "user15" => null,
            "user16" => null,
            "user17" => null,
            "user18" => null,
            "user19" => null,
            "user20" => null
        ));

        Contract::create(array(
            "web_id" => "7",
            "code" => "15055",
            "cname" => "Grand Mall",
            "name" => "15055 - Grand Mall",
            "created_time" => "2014-02-15 10:07:15",
            "update_time" => "2014-05-08 11:57:12",
            "customer" => "General",
            "website" => "Main Website",
            "store" => "Default Store View",
            "name_bill" => "36 Strategies",
            "street_bill" => "H Hotel Office Tower",
            "street1_bill" => "Sheikh Zayed Road, Suite 2002",
            "city_bill" => "Dubai",
            "country_bill" => "AE",
            "zip_bill" => null,
            "name_ship1" => "36S",
            "street_ship1" => "36S",
            "street1_ship1" => "SZR",
            "city_ship1" => "Dubai",
            "country_ship1" => "AE",
            "zip_ship1" => null,
            "name_ship2" => "36S2",
            "street_ship2" => "36S2",
            "street1_ship2" => "36S2-L2",
            "city_ship2" => "Dubai",
            "country_ship2" => "AE",
            "zip_ship2" => null,
            "name_ship3" => null,
            "street_ship3" => null,
            "street1_ship3" => null,
            "city_ship3" => null,
            "country_ship3" => "0",
            "zip_ship3" => null,
            "name_ship4" => null,
            "street_ship4" => null,
            "street1_ship4" => null,
            "city_ship4" => null,
            "country_ship4" => "0",
            "zip_ship4" => null,
            "name_ship5" => null,
            "street_ship5" => null,
            "street1_ship5" => null,
            "city_ship5" => null,
            "country_ship5" => "0",
            "zip_ship5" => null,
            "user1" => "36S Storekeeper",
            "user2" => "36S Project Manager",
            "user3" => "36S Finance Manager",
            "user4" => null,
            "user5" => null,
            "user6" => null,
            "user7" => null,
            "user8" => null,
            "user9" => null,
            "user10" => null,
            "user11" => null,
            "user12" => null,
            "user13" => null,
            "user14" => null,
            "user15" => null,
            "user16" => null,
            "user17" => null,
            "user18" => null,
            "user19" => null,
            "user20" => null
        ));

    }
}